name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.Ram3shbabuvv99 }}" | docker login -u "${{ secrets.RAMESHBABUVV }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.RAMESHBABUVV }}/minidrive-docker .

      - name: Push Docker image
        run: docker push ${{ secrets.RAMESHBABUVV }}/minidrive-docker