name: CI - Build Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minidrive .
      - name: Run container
        run: docker run -d -p 5000:5000 minidrive

      - name: Test app
        run: |
         sleep 5
         curl http://localhost:5000